{u'description': [u"alunduil's personal overlay"],
 u'feeds': [u'https://github.com/alunduil/alunduil-overlay/commits/master.atom'],
 u'homepage': u'https://github.com/alunduil/alunduil-overlay',
 u'irc': None,
 u'name': u'alunduil',
 u'official': True,
 u'owner_email': u'alunduil@gentoo.org',
 u'owner_name': u'Alex Brandt',
 u'priority': 50,
 u'quality': u'experimental',
 u'sources': [(u'https://github.com/alunduil/alunduil-overlay.git',
               u'Git',
               u''),
              (u'git://github.com/alunduil/alunduil-overlay.git',
               u'Git',
               u''),
              (u'git@github.com:alunduil/alunduil-overlay.git', u'Git', u'')],
 u'status': u'official',
 u'supported': True}
$ pmaint sync alunduil
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
From https://github.com/alunduil/alunduil-overlay
   2a932c5..90fc0cf  master     -> origin/master
Updating 2a932c5..90fc0cf
Fast-forward
 dev-python/debtcollector/Manifest                           |  4 ++--
 ...ebtcollector-0.5.0.ebuild => debtcollector-0.6.0.ebuild} | 13 ++++++-------
 dev-python/docker-py/Manifest                               |  2 +-
 dev-python/docker-py/docker-py-1.3.1.ebuild                 |  5 ++++-
 dev-python/oslo-utils/Manifest                              |  2 +-
 dev-python/oslo-utils/oslo-utils-2.1.0.ebuild               |  4 ++--
 6 files changed, 16 insertions(+), 14 deletions(-)
 rename dev-python/debtcollector/{debtcollector-0.5.0.ebuild => debtcollector-0.6.0.ebuild} (84%)
*** syncing alunduil
*** synced alunduil
 * Sync succeeded
$ pmaint regen -t 2 alunduil
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: media-fonts/monoid-9999
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/nose2-0.5.0
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: app-portage/etest-9999!!! 
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/aiohttp-0.16.6
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-config-2.0.0
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/debtcollector-0.6.0
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: app-emulation/docker-compose-1.3.3
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/os-client-config-1.4.0
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-utils-2.1.0
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-serialization-1.7.0!!! 
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslo-i18n-2.1.0
!!! !!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/pyhamcrest-1.8.5
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/python-termstyle-0.1.10
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/docker-py-1.3.1
!!! caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: app-backup/holland-backup-xtrabackup-1.0.10
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/oslotest-1.9.0
caught exception bytes_ro_StringIO instance has no attribute '__len__' while processing ebuild src: dev-python/supernova-2.0.3
 * Cache regenerated successfully
