{u'description': [u'Personal overlay of Erik Moen'],
 u'feeds': [u'https://cgit.gentoo.org/user/eroen.git/atom/'],
 u'homepage': u'https://cgit.gentoo.org/user/eroen.git/',
 u'irc': None,
 u'name': u'eroen',
 u'official': False,
 u'owner_email': u'gentoo@eroen.eu',
 u'owner_name': u'Erik Moen',
 u'priority': 50,
 u'quality': u'experimental',
 u'sources': [(u'git://anongit.gentoo.org/user/eroen.git', u'Git', u''),
              (u'https://anongit.gentoo.org/git/user/eroen.git', u'Git', u''),
              (u'git+ssh://git@git.gentoo.org/user/eroen.git', u'Git', u'')],
 u'status': u'unofficial',
 u'supported': True}
$ pmaint sync /home/mgorny/repos/eroen
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has an unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has an unsupported profile format(s): 'profile-set'
Already up-to-date.
*** syncing '/home/mgorny/repos/eroen'...
*** synced '/home/mgorny/repos/eroen'
 * Sync succeeded
$ pmaint regen -t 2 eroen
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has an unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has an unsupported profile format(s): 'profile-set'

!!! ERROR: dev-python/pyffi-2.2.2 failed.
!!! die invoked from directory /usr/lib64/pkgcore
!!! Call stack:

!!! ERROR: app-cdr/k3b-2.0.2-r4 failed.
!!! die invoked from directory /usr/lib64/pkgcore
!!! Call stack:
!!!             ebuild-daemon.bash, line 451:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 451:  Called __ebd_exec_main 'daemonize'
!!!             ebuild-daemon.bash, line 209:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 209:  Called __ebd_main_loop
!!!             ebuild-daemon.bash, line 437:  Called __ebd_process_metadata '169' 'depend'
!!!             ebuild-daemon.bash, line 437:  Called __ebd_process_metadata '162' 'depend'
!!!             ebuild-daemon.bash, line 370:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 426:  Called __load_ebuild '/home/mgorny/repos/eroen/dev-python/pyffi/pyffi-2.2.2.ebuild'
!!!             ebuild-daemon.bash, line 370:  Called __execute_phases 'depend'
!!!                     ebuild.lib, line 426:  Called __load_ebuild '/home/mgorny/repos/eroen/app-cdr/k3b/k3b-2.0.2-r4.ebuild'
!!!                     ebuild.lib, line 241:  Called __qa_invoke 'source' '/home/mgorny/repos/eroen/dev-python/pyffi/pyffi-2.2.2.ebuild'
!!!         isolated-functions.lib, line 221:  Called source '/home/mgorny/repos/eroen/dev-python/pyffi/pyffi-2.2.2.ebuild'
!!!             pyffi-2.2.2.ebuild, line  13:  Called inherit 'eutils' 'distutils-r1'
!!!                     ebuild.lib, line 241:  Called __qa_invoke 'source' '/home/mgorny/repos/eroen/app-cdr/k3b/k3b-2.0.2-r4.ebuild'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'distutils-r1'
!!!         isolated-functions.lib, line 221:  Called source '/home/mgorny/repos/eroen/app-cdr/k3b/k3b-2.0.2-r4.ebuild'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/distutils-r1.eclass'
!!!            k3b-2.0.2-r4.ebuild, line  25:  Called inherit 'kde4-base'
!!!         isolated-functions.lib, line 221:  Called source '/home/mgorny/repos/gentoo/eclass/distutils-r1.eclass'
!!!            distutils-r1.eclass, line  85:  Called inherit 'multiprocessing' 'python-r1'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'kde4-base'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'python-r1'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/python-r1.eclass'
!!!         isolated-functions.lib, line 221:  Called source '/home/mgorny/repos/gentoo/eclass/python-r1.eclass'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/kde4-base.eclass'
!!!         isolated-functions.lib, line 221:  Called source '/home/mgorny/repos/gentoo/eclass/kde4-base.eclass'
!!!               python-r1.eclass, line 232:  Called _python_set_globals
!!!               python-r1.eclass, line 199:  Called die
!!! The die message:
!!!  No supported implementation in PYTHON_COMPAT.

!!!               kde4-base.eclass, line  37:  Called inherit 'kde4-functions' 'toolchain-funcs' 'fdo-mime' 'flag-o-matic' 'gnome2-utils' 'virtualx' 'versionator' 'eutils' 'multilib'
!!!   ebuild-default-functions.lib, line 230:  Called __internal_inherit 'kde4-functions'
!!!              ebuild-daemon.lib, line  30:  Called __qa_invoke 'source' '/home/mgorny/repos/gentoo/eclass/kde4-functions.eclass'
!!!         isolated-functions.lib, line 221:  Called source '/home/mgorny/repos/gentoo/eclass/kde4-functions.eclass'
!!!          kde4-functions.eclass, line  23:  Called die
!!! The die message:
!!!  EAPI=4 is not supported

ERROR pkgcore: returned val from gen_metadata was 'False'
!!! caught exception False while processing ebuild src: dev-python/pyffi-2.2.2
ERROR pkgcore: returned val from gen_metadata was 'False'
!!! caught exception False while processing ebuild src: app-cdr/k3b-2.0.2-r4
 * Cache regenerated successfully
