{u'description': [u'dev-python/netzob and maybe some i3 hacks'],
 u'feeds': [u'https://cgit.gentoo.org/user/lootr.git/atom/'],
 u'homepage': u'https://cgit.gentoo.org/user/lootr.git/',
 u'irc': None,
 u'name': u'lootr',
 u'official': False,
 u'owner_email': u'alex@freesenses.net',
 u'owner_name': u'Alexandre PIGN\xc9',
 u'priority': 50,
 u'quality': u'experimental',
 u'sources': [(u'git://anongit.gentoo.org/user/lootr.git', u'Git', u''),
              (u'https://anongit.gentoo.org/git/user/lootr.git', u'Git', u''),
              (u'git+ssh://git@git.gentoo.org/user/lootr.git', u'Git', u'')],
 u'status': u'unofficial',
 u'supported': True}
$ pmaint sync lootr
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
Already up-to-date.
*** syncing lootr
*** synced lootr
 * Sync succeeded
$ pmaint regen -t 2 lootr
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
WARNING:pkgcore:repository at '/home/mgorny/repos/steveeJ' has unsupported profile format(s): 'profile-set'
Error running an operation:
 Unhandled exception in regen_cache
 [Errno 13] Permission denied
coms error in 8318, read_line com failed w/ 1: backing out of daemon.
 * Cache regen failed with 246
